### ISSUE TITLE
Unable to block localhost

### ISSUE THREAD

**Issue by MBurchard** [kainsavage/HistoryBlock#34]
I'm working as a developer and my Firefox chronic is full of localhost entries.
Today I deleted nearly 15.000.
I search for a better solution and found and installed HistoryBlock.
But it is not possible to add localhost as a domain that can be blocked.
What about doing a pattern matching, like all the Adblockers do. It should allow the user to save a regular expression that can be blocked then...

**Comment by MBurchard** [comment]
If you renounce the SHA1 hash, which is no longer up-to-date anyway, one can implement pattern matching.
I would change the structure in such a way that the user no longer has to maintain a certain type of blocking list as it is today, but can see from the entries themselves what has to be blocked.
So you can easily distinguish domains from subdomains and complete URLs.
These can then be hashed somehow in order to maintain the level of pseudo security.
Of course you can't hash a pattern for matching, here you would have to go more in the direction of encryption, but in my opinion this goes over the top, because nobody needs it.
Who wants to surf porn sites should use the private mode ;)

**Comment by kainsavage** [comment]
I will fix the localhost issue, and have plans for an SHA256 implementation. Closing in favor of #31
