### ISSUE TITLE
Any chance to have it for chrome?

### ISSUE THREAD

**Issue by erkange** [kainsavage/HistoryBlock#37]
We would like to use it in chrome too

**Comment by kainsavage** [comment]
As far as I am aware, Chrome does not support the specific API required to enable HistoryBlock to work.

[forgetClosedTab](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/forgetClosedTab) is pretty much the linchpin for the whole addon, and Firefox is the only browser than supports it (at my request, kind of hilariously...).

Feel free to re-open if any other browser supports it, but this is basically a non-starter for now.
